### ISSUE TITLE
Can't compile on Mac

### ISSUE THREAD

**Issue by raresn** [airsdk/Adobe-Runtime-Support#4043]
I am using iphoneOS26.0.sdk in the ios platform sdk, and AIR51.1.4

sh apple-store.sh
->
WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
0  0x105910718  __assert_rtn + 166
1  0x10591d693  ld::tool::SymbolTableAtom<arm64>::classicOrdinalForProxy(ld::Atom const*) (.cold.2) + 35
2  0x1058146a7  ld::tool::SymbolTableAtom<arm64>::classicOrdinalForProxy(ld::Atom const*) + 167
3  0x105813ed5  ld::tool::SymbolTableAtom<arm64>::addImport(ld::Atom const*, ld::tool::StringPoolAtom*) + 101
4  0x105813826  ld::tool::SymbolTableAtom<arm64>::encode() + 486
5  0x105801a6e  ___ZN2ld4tool10OutputFile20buildLINKEDITContentERNS_8InternalE_block_invoke.413 + 30
6  0x7ff8038606b9  _dispatch_call_block_and_release + 12
7  0x7ff803876bee  _dispatch_client_callout + 6
8  0x7ff803891a02  _dispatch_root_queue_drain.cold.3 + 931
9  0x7ff80386fb90  _dispatch_root_queue_drain + 98
10  0x7ff80387002a  _dispatch_worker_thread2 + 174
11  0x7ff803a17828  _pthread_wqthread + 233
A linker snapshot was created at:
	/tmp/aot15674163051750610447.tmp-2025-10-29-144148.ld-snapshot
ld: Assertion failed: (it != _dylibToOrdinal.end()), function dylibToOrdinal, file OutputFile.cpp, line 5196.

Compilation failed while executing : ld64

Stuck here - anyone has a clue what i can do?

**Comment by raresn** [comment]
Apparently it's because of some extension i am using. I removed the extension from the xml + used a small swf and it compiled. 
@marchbold do you have any idea what could cause this?
    <extensionID>com.android.installreferrer</extensionID>
    <extensionID>com.distriqt.Application</extensionID>
    <extensionID>com.distriqt.CameraRollExtended</extensionID>
    <extensionID>com.distriqt.Contacts</extensionID>
    <extensionID>com.distriqt.Core</extensionID>
    <extensionID>com.distriqt.Firebase</extensionID>
    <extensionID>com.distriqt.IDFA</extensionID>
    <extensionID>com.distriqt.InAppBilling</extensionID>
    <extensionID>com.distriqt.PushNotifications</extensionID>
    <extensionID>com.distriqt.firebase.Auth</extensionID>
    <extensionID>com.distriqt.firebase.Crashlytics</extensionID>
    <extensionID>com.distriqt.firebase.Database</extensionID>
    <extensionID>com.distriqt.square.okhttp</extensionID>
    <extensionID>com.distriqt.square.okhttp3</extensionID>
    <extensionID>com.distriqt.square.picasso</extensionID>
    <extensionID>com.google.android.play.appupdate</extensionID>
    <extensionID>com.google.firebase.core</extensionID>
    <extensionID>com.google.firebase.messaging</extensionID>
These are the extensions I am using.

**Comment by raresn** [comment]
@ajwfrost  - i tried publishing the above with 51.1.4 and it fails, but it works with 51.2.2
Anything i can do?

**Comment by marchbold** [comment]
I would suggest using the iOS 18 sdk until all the underlying SDKs are updated to the recent release. Does it work if you use 18?

**Comment by raresn** [comment]
For anyone reading this and not knowing how MAC OS works, you can just get a copy of an SDK and drop it somewhere, then using AIR SDK manager point to that specific SDK

**Comment by raresn** [comment]
It compiled with SDK 18.5 - so thats safe for us to use/relase a new version?

**Comment by marchbold** [comment]
Yes using 18.x should be fine currently. I just don't believe a lot of the SDKs we wrap have updated to 26 yet so I imagine there will be issues using that currently.

**Comment by ajwfrost** [comment]
@raresn interesting to see it's actually crashed the Apple linker!

>  i tried publishing the above with 51.1.4 and it fails, but it works with 51.2.2

Would you be able to post the ADT log output for these builds, specifically the "ld64 command line" entries? I'm wondering whether there's any obvious difference that might account for the difference in behaviour..

thanks

**Comment by marchbold** [comment]
@raresn Can I just confirm that this issue was solely because of iOS 26? 

I'll start looking into migration paths for the SDKs and see when updates are being released for iOS 26.

**Comment by raresn** [comment]
I confirm thats the only change
