### ISSUE TITLE
 error 102: Invalid namespace http://ns.adobe.com/air/application/50.0

### ISSUE THREAD

**Issue by attacker88** [airsdk/Adobe-Runtime-Support#2336]
I am getting this error  102: Invalid namespace http://ns.adobe.com/air/application/50.0 when creating an ipa.
Im using flex 4.14.1 and AirSdk 50.0.1.3. 
This issue wasnt previously there when i was using AirSdk  33.1.1.620.
Im defining <application xmlns="http://ns.adobe.com/air/application/50.0"> in my application.

I get this error when I run the command "adt -package -target ipa-ad-hoc -storetype pkcs12 -keystore MYEnterpriseDistribution2023.p12 -provisioning-profile MYProfile_6Jul2023_com.my.in.star.mobileprovision iPad.ipa iPad-app.xml iPad.swf Default.png Assets.car -extdir C:\Users\xyz\Documents\libs"

As i said it used to work fine with AirSdk 33.1.1.620 and <application xmlns="http://ns.adobe.com/air/application/33.1">

**Comment by ajwfrost** [comment]
Hi

If the application has the 50.0 namespace in its application descriptor file, then it wouldn't work with AIR 33.1 or earlier.. possibly if you're using Animate or similar, it may have been auto updated?

But the 50.0 namespace should work with the 50.0 version of ADT! Where you run that `adt -package` command, can you run `adt -version` to just check what is being picked up? Or if you stick an error into it somewhere (if you're using Animate or similar - try prefixing a filename with a - symbol perhaps?) then the error message should display the ADT version number.

thanks

**Comment by attacker88** [comment]
Hi , Sorry the issue was from my end as i didnt update the environment variable with the lastest airsdk.

There is one more issue, the IPA created using Air 50.0.1.3 isnt working on ios 16.
when will the new version come out in support for ios 16

**Comment by ajwfrost** [comment]
Thanks 

"isn't working on ios 16" sounds like it doesn't launch at all..? I know we have some issues (e.g. orientation) but we have plenty of AIR apps built with earlier SDK versions that are running on iOS16 devices. Are you able to confirm exactly what's wrong?

Plus -> please try the release from our 50.1 branch which updates all the iOS/macOS support. The reason we've not yet set this as "current" is because you can't use Windows for iOS development using this, as the linker is too old...
https://airsdk.harman.com/download/50.1.1.1

thanks

**Comment by attacker88** [comment]
The issue is IPA is not getting installed on ipad with IOS 16 and seems to work fine with lower ios versions.
Also I tried the latest release i.e. [https://airsdk.harman.com/download/50.1.1.1) and I'm using windows.
I got compilation error "Undefined symbols for architecture arm64"

**Comment by ajwfrost** [comment]
So yes, the compilation error on Windows is expected, we are working on a Windows build of the latest available Apple Linker..

Not installing on iOS 16.1 is odd, do you see any error message? Can you try installing it by doing the following in a Windows command prompt:
```
cd (wherever your AIR SDK is located)
cd lib\aot\bin\iOSBin
ideviceinstaller -i path_to_ipa_file
```
This should then give the below sort of output but will stop on the stage that caused the error:
```
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/appname.app/SC_Info/appname.sinf in archive!
Copying 'appname.ipa' to device... DONE.
Installing 'appid'
Install: CreatingStagingDirectory (5%)
Install: ExtractingPackage (15%)
Install: InspectingPackage (20%)
Install: PreflightingApplication (30%)
Install: VerifyingApplication (40%)
Install: CreatingContainer (50%)
Install: InstallingApplication (60%)
Install: PostflightingApplication (70%)
Install: SandboxingApplication (80%)
Install: GeneratingApplicationMap (90%)
Install: InstallComplete (100%)
Install: Complete
```

thanks

**Comment by attacker88** [comment]
Thanks, will try this out in sometime and let you know as the IPAD is having some issues.
Also ,When can we expect the 50.1.1.1 for windows build.

**Comment by ajwfrost** [comment]
The Windows build of the Apple linker is proving challenging :-(
We're trying a few different approaches, and getting some support from Adobe on it, I'm hoping we'll get it out before Christmas.

thanks

**Comment by attacker88** [comment]
Hi @ajwfrost 
is there anything apart from the below commands that we can try? we are facing few issues with ideviceinstaller. 

```
cd (wherever your AIR SDK is located)
cd lib\aot\bin\iOSBin
ideviceinstaller -i path_to_ipa_file
```
we also tried the latest build 50.1.1.1 with mac to build the IPA to support devices with ios 16. Its still not working and throws an error saying "unable to install"
![Ios_16_issue](https://user-images.githubusercontent.com/66474039/206389813-4255b412-86bc-4e21-8b8b-ef086a292cbd.png)

**Comment by attacker88** [comment]
Thanks for the help @ajwfrost with the StackOverflow link you had provided. 
Issue was with the app ID for enterprise distribution.

**Comment by ajwfrost** [comment]
Okay great, thanks for confirming -> closing this one as I think all the issues are resolved now? 
thanks
