### ISSUE TITLE
Xcode 12 Simulator 14.2 still not working with 33.1.1.406

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#714]
When trying to test the app with Xcode 12 there is still this error message:
Packaging failed!
Packaging error message: 
Compilation failed while executing : ld64
Packaging output: 
ld: in /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/../../../../../usr/lib/llvm-gcc/4.2.1/libgcc.a(libgcc.o), building for iOS/iOS Simulator, but linking in object file built for macOS, file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/../../../../../usr/lib/llvm-gcc/4.2.1/libgcc.a' for architecture x86_64

How long do we have to use the Xcode on Mojave????

**Comment by ajwfrost** [comment]
Hi @apofis1969  - are you able to try replacing your adt.jar file from [sdk_folder]/lib, with the one from the below message?
thanks
https://transfer.harman.com/message/A30SIcuQ5NoPo9KyE3QQxA

**Comment by apofis1969** [comment]
@ajwfrost hi, downloaded. Will test it tomorrow and tell you. Thanks a lot

**Comment by apofis1969** [comment]
@ajwfrost copied the file into the sdk. Received this error message:
Packaging failed!
Packaging error message: 
Compilation failed while executing : ld64
Packaging output: 
ld: building for iOS/iOS Simulator, but linking in object file built for iOS Simulator, file 'extensionglue.o' for architecture x86_64

**Comment by ajwfrost** [comment]
Okay well that's different! Thanks for that, we'll take a look at what happens with ANEs then..

**Comment by ajwfrost** [comment]
Hi @apofis1969 - this is a bit of a tricky one as we don't actually see the same thing happening here..

The error from the linker suggests that we are building an output for both iOS and the simulator, but we are only linking in a file that was build for the simulator - because the extensionglue.o file (generated by our AOT compiler) is just for the simulator as it's x86_64.

We believe that the correct approach is to tell the linker that we are just generating a file for the simulator so that it ignores the idea of building for the 'normal' iOS target itself.. (according to the documentation, it should only ever have one target, so quite how it thinks it's linking for two things is a bit odd). So there's a potential update we can make to the linker command line to try to get this to work; if that fails, we may need to go higher and use clang to do the linking instead.

Personally I'd be happier if we could reproduce that here, I'm not quite sure why we can't: are you able to confirm the exact versions you have for macOS, Xcode and the simulator SDK (14.2 I guess)? In the meantime, we'll get an updated jar file with the change to the ld command line..

thanks

**Comment by ajwfrost** [comment]
@apofis1969  please try the below jar file:
https://transfer.harman.com/message/qhYaztL37nVk3buy1EHv61
thanks

**Comment by apofis1969** [comment]
Hi @ajwfrost 
I am using Xcode Version 12.2 (12B45b)
macOS 10.15.7
With the new adt.jar I get this error message:
ackaging failed!
Packaging error message: 
Compilation failed while executing : ld64
Packaging output: 
ld: in /Volumes/Sicherung/a-PetCam/fdt/air33/sdk33.1.1.406/sdk33-1-406/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a(CTGameInput.o), building for iOS/iOS Simulator, but linking in object file built for iOS Simulator, file '/Volumes/Sicherung/a-PetCam/fdt/air33/sdk33.1.1.406/sdk33-1-406/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a' for architecture x86_64

**Comment by buyANE** [comment]
@ajwfrost  It's because the ANE they use, some ane have <option>-ios_version_min 9.0</option> in there platform.xml, when compile ipa use lastest MacOS,It will get error like "building for iOS/iOS Simulator, but linking in object file built for iOS Simulator, file '/Volumes/Sicherung/a-PetCam/fdt/air33/sdk33.1.1.406/sdk33-1-406/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a' for architecture x86_64" , so to get this error gone, the ane should be repackaged and remove <option>-ios_version_min 9.0</option> in ane's platform.xml file.

**Comment by marchbold** [comment]
@buyANE I disagree, I believe libraries such as ANEs should still have the ability to set a minimum SDK but that AIR should pick the highest value at package time.  Removing it from the ANEs is not logical as it serves a purpose. If this is the issue (which I'm not certain it is) then it's an issue in the packaging process.

**Comment by ajwfrost** [comment]
.. and just to add to this: we had adjusted the command line in the latest test version of ADT so that it's not using ios_version_min (as that's a bit outdated now), instead we're using the platform_version ios-simulator command. I'll check what version it was, in case this does make a difference though, and will also look at the logic there.

The test case here doesn't include any ANEs though (at least, when we started looking at this issue, we were getting that initial problem as reported on 2nd March but just as a 'warning' rather than as an error, and our test case was just a simple hello world..

**Comment by buyANE** [comment]
@marchbold I don‘t thinks use ios_version_min in platform.xml is a good idea, As this have cause problem when Adobe change Default MinimumOSVersion to 8.0 in AIR 28（at that time many ANEs have ios_version_min 6.0 in there ANE’s platform.xml）. Of course AIR can pick the highest value as package time is better,but even without it,we can still do what we can and get rid of this  type of error.
currently the Default MinimumOSVersion is 9.0 when generate ipa file, so it's unnecessary to set -ios_version_min 9.0 in ANE's platform.xml file

**Comment by ajwfrost** [comment]
@apofis1969  with the above in mind .. are you able to update your Application's XML descriptor file to add an element into your InfoAdditions section:
```
<key>MinimumOSVersion</key>
<string>11.0</string>
```
or similar? and try that using the latest jar file I'd sent?

thanks

**Comment by tuarua** [comment]
I tested the above adt.jar and setting MinimumOSVersion to 11.0 in app.xml I was able to run a basic project in the Simulator.

When I added an ANE I got the error back but I resolved this by removing `<option>-ios_version_min 11.0</option>` completely from the platform.xml

N.B. I was using Simulator 12.4 on Big Sur 

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk

**Comment by apofis1969** [comment]
@ajwfrost Hi, using 11.0 as minimum version creates this error while trying to launch the simulators.
Packaging failed!
Packaging error message: 
Compilation failed while executing : ld64
Packaging output: 
ld: building for iOS/iOS Simulator, but linking in object file built for iOS Simulator, file 'extensionglue.o' for architecture x86_64

**Comment by ajwfrost** [comment]
Hi @apofis1969  - just to check, it looks like there are three things needed (currently) for the fix:
a) ANEs with the "ios_version_min" removed from their linker options
b) updated application descriptor file with added MinimumOSVersion string in InfoAdditions
c) updated ADT jar file from above that is switching to use "ios-simulator" link target

Can I check that you definitely did the first two of these..?

thanks

**Comment by apofis1969** [comment]
@ajwfrost hi
a) ANEs with the "ios_version_min" removed from their linker options
How to do that, where do I have to add this?
b) done
c) done

**Comment by ajwfrost** [comment]
@apofis1969 this should be resolved now I believe, with the latest SDK releases - are you able to check and if you're still having problems, please re-open the ticket?
thanks
