### ISSUE TITLE
After updating AIR SDK to version 50.2.4.5 Huge Spike in Crashes on iOS devices

### ISSUE THREAD

**Issue by Tuning3DT** [airsdk/Adobe-Runtime-Support#3208]
After updating the AIR SDK crashes on ios devices increased tremendously. 
It crashes randomly even if the app is just open and not being used actively. 
Crashes occur on different devices old and new, mainly with iOS17+ but there are iOS15 and 16 too. 
I tried setting iOSPlatformSDK to point to the iOS SDK but it didn't help.
I'm using Intellij IDEA to compile the IPA file.
Before updating I was building with 50.2.3.1 and there was no issue with it crashes were incomparably low.

AIR SDK: 50.2.4.5
macOS Monterey 12.7.2
IDE: Intellij IDEA 
xcode 14.2
JVM 18.0.2.1

These are some of the stack traces of the most occurring crashes.

[com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_6e1903e247454530b2a7527d10d3bb13_DNE_0_v2_stacktrace (1).txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15137921/com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_6e1903e247454530b2a7527d10d3bb13_DNE_0_v2_stacktrace.1.txt)
[com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_6e1903e247454530b2a7527d10d3bb13_DNE_0_v2_stacktrace.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15137922/com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_6e1903e247454530b2a7527d10d3bb13_DNE_0_v2_stacktrace.txt)
[com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_28c979861b06448ba2de12d45b78b5c6_DNE_0_v2_stacktrace.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15137923/com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_28c979861b06448ba2de12d45b78b5c6_DNE_0_v2_stacktrace.txt)
[com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_90ab2a8b4fd544b28649fdd30108274b_DNE_0_v2_stacktrace.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15137924/com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_90ab2a8b4fd544b28649fdd30108274b_DNE_0_v2_stacktrace.txt)
[com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_f953fc3b38ad4cc4851539b920a99417_DNE_0_v2_stacktrace.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15137925/com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_f953fc3b38ad4cc4851539b920a99417_DNE_0_v2_stacktrace.txt)

**Comment by ajwfrost** [comment]
These are all crashes within/after "objc_msgSend" which is the new(ish) mechanism Apple had switched to using in Xcode 14. We already know there are issues with missing symbols that happen because of how the updated linker works now, which means that Windows build (using the LLVM ld64 linker) can cause problems particularly on older iOS versions. But on macOS we should be switching to use the Apple ld64 linker (named "ld-classic", on newer Xcode releases, I think from 15).

I would suggest the best option is to update to the latest Xcode - and particularly to the latest iPhoneOS SDK version - and rebuild, using that -platformsdk option. There's perhaps an issue here where your app is building against an older iPhoneOS (from Xcode 14.2) but the IPA - and its executable file - would probably specify that it's built with the latest version, because that's something we inject during linking. This mismatch could be the culprit..

It would be great if we could just ensure absolutely everyone has the same build environment for all this..! Several different combinations/permutations are possible which makes it tricky.

If you can try with the updated iPhoneOS SDK to start with, please capture the build comments from within ADT (using AIR SDK Manager "Troubleshooting" tab) and we can check what the linker is actually doing..

thanks

**Comment by Tuning3DT** [comment]
@ajwfrost I did exactly what you said but the app crashes on start. It got event worse.
Here is the SDK ManagerTroubleshooting fool report.
There are no errors during the compiling and uploading processes. The first time I created and uploaded the IPA file it was working fine and didn't crashes. After that however anytime I create and upload a new build it just won't open. Crashes immediately. 

```

ld64 command line: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld-classic -pie -ObjC -dead_strip -Z -arch arm64 -syslibroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk" -L/usr/lib -L/usr/lib/swift -F"/System/Library/Frameworks" -L"/Users/tigranmakaryan/Projects/Tuning/app/AIRSDK_MacOS/lib/aot/lib" -o "../aot3769842375576684706.tmp" -x "/Users/tigranmakaryan/Projects/Tuning/app/AIRSDK_MacOS/lib/aot/lib/libRuntimeHMAOT.arm-air.a" "/Users/tigranmakaryan/Projects/Tuning/app/AIRSDK_MacOS/lib/aot/lib/libNotification.arm-air.a" -lc++ -lSystem.B -lz -lobjc -lclang_rt.ios -weak_framework AppTrackingTransparency -framework AdSupport -w -weak_framework SafariServices -framework WebKit "-F/var/folders/70/c91x_vtj0t31vyvyn__jqqdw0000gn/T/04e21748-b781-4a61-9bf0-fe44a2cc26bc" -framework "Bolts" -lsqlite3 -lz -framework SystemConfiguration -framework StoreKit -framework Security -framework CoreTelephony -framework CoreData -framework "FirebaseCore" -framework "FirebaseCoreDiagnostics" -framework "FirebaseInstallations" -framework "GoogleAppMeasurement" -framework "GoogleDataTransport" -framework "GoogleUtilities" -framework "nanopb" -framework "PromisesObjC" -ObjC -lz -lsqlite3 -w -framework "FirebaseCrashlytics" -w -framework CoreHaptics -w -weak_framework ReplayKit -framework GameKit -w -weak_framework iAd -framework JavaScriptCore -framework GLKit -framework SafariServices -framework MediaPlayer -framework MessageUI -framework CoreVideo -framework CoreMotion -framework CoreGraphics -framework AudioToolbox -framework AVFoundation -framework "GoogleAppMeasurementIdentitySupport" -framework "GoogleMobileAds" -framework "UserMessagingPlatform" -framework Accounts -framework Social -framework ImageIO -w -framework "FirebaseAnalytics" -framework "FBSDKLoginKit" -framework UserNotifications -framework AddressBook -framework "FirebaseABTesting" -framework "FirebaseInAppMessaging" -framework "FirebaseMessaging" -framework PhotosUI -framework Photos -framework AssetsLibrary -framework QuartzCore -w -w -lclang_rt.ios -ObjC -weak_framework UserNotifications -w -framework "CoreNativeExtension" -rpath @executable_path/Frameworks -weak_framework Social -framework AuthenticationServices -framework Accelerate -framework "FBAEMKit" -framework "FBSDKCoreKit" -framework "FBSDKCoreKit_Basics" -framework "FBSDKShareKit" -w -weak_framework AVFoundation -weak_framework AVKit -filelist "/Users/tigranmakaryan/Projects/Tuning/app/tuningAppAs/bin-debug/AOTBuildOutput16651481924351827416.tmp/OBJFilesList.txt" -framework CoreFoundation -framework UIKit -framework MobileCoreServices -framework Foundation -framework CFNetwork -framework OpenGLES -framework CoreLocation -framework CoreMedia -framework GameController -platform_version ios 12.2 17.4 -exported_symbols_list "/Users/tigranmakaryan/Projects/Tuning/app/tuningAppAs/bin-debug/AOTBuildOutput16651481924351827416.tmp/SYMFilesList.txt"


dsymutil command line: dsymutil -o /Users/tigranmakaryan/Projects/Tuning/app/tuningAppAs/bin-debug/3DTuning.app.dSYM /Users/tigranmakaryan/Projects/Tuning/app/tuningAppAs/bin-debug/aot3769842375576684706.tmp

warning: (arm64) /tmp/bitcode_strip.dl3tqA unable to open object file: No such file or directory
warning: (arm64)  could not find object file symbol for symbol +[DTFREImageUtils writeBitmapDataToTmpFile:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREImageUtils createUIImageFromBitmapData:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREImageUtils createUIImageFromBitmapData:cacheInternally:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREImageUtils newFREBitmapDataFromUIImage:]
warning: (arm64)  could not find object file symbol for symbol __OBJC_$_CLASS_METHODS_DTFREImageUtils
warning: (arm64)  could not find object file symbol for symbol __OBJC_METACLASS_RO_$_DTFREImageUtils
warning: (arm64)  could not find object file symbol for symbol __OBJC_CLASS_RO_$_DTFREImageUtils
warning: (arm64)  could not find object file symbol for symbol _OBJC_CLASS_$_DTFREImageUtils
warning: (arm64)  could not find object file symbol for symbol _OBJC_METACLASS_$_DTFREImageUtils
warning: (arm64) /tmp/bitcode_strip.QrGzbC unable to open object file: No such file or directory
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils_Internal log:message:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils_Internal initDataWithString:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils_Internal newFREObjectFromObject:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils_Internal newFREObjectFromString:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils_Internal newFREObjectFromInt:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils_Internal newFREObjectFromLong:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils_Internal newFREObjectFromBoolean:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils_Internal newFREObjectFromDouble:]
warning: (arm64)  could not find object file symbol for symbol __OBJC_$_CLASS_METHODS_DTFREUtils_Internal
warning: (arm64)  could not find object file symbol for symbol __OBJC_METACLASS_RO_$_DTFREUtils_Internal
warning: (arm64)  could not find object file symbol for symbol __OBJC_CLASS_RO_$_DTFREUtils_Internal
warning: (arm64)  could not find object file symbol for symbol _OBJC_CLASS_$_DTFREUtils_Internal
warning: (arm64)  could not find object file symbol for symbol _OBJC_METACLASS_$_DTFREUtils_Internal
warning: (arm64) /tmp/bitcode_strip.hCXF3u unable to open object file: No such file or directory
warning: (arm64)  could not find object file symbol for symbol +[DTJSONUtils dictToJSONString:]
warning: (arm64)  could not find object file symbol for symbol +[DTJSONUtils jsonStringToDict:]
warning: (arm64)  could not find object file symbol for symbol __OBJC_$_CLASS_METHODS_DTJSONUtils
warning: (arm64)  could not find object file symbol for symbol __OBJC_METACLASS_RO_$_DTJSONUtils
warning: (arm64)  could not find object file symbol for symbol __OBJC_CLASS_RO_$_DTJSONUtils
warning: (arm64)  could not find object file symbol for symbol _OBJC_METACLASS_$_DTJSONUtils
warning: (arm64)  could not find object file symbol for symbol _OBJC_CLASS_$_DTJSONUtils
warning: (arm64) /tmp/bitcode_strip.t4UESE unable to open object file: No such file or directory
warning: (arm64)  could not find object file symbol for symbol +[DTNotifications load]
warning: (arm64)  could not find object file symbol for symbol +[DTNotifications didFinishLaunchingWithOptionsNotificationHandler:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications init]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications checkLaunchOptions]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications addObservers]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications removeObservers]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications didRegisterForRemoteNotificationsWithDeviceToken:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications didRegisterUserNotificationSettings:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications didFailToRegisterForRemoteNotificationsWithError:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications didReceiveRemoteNotification:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications didReceiveRemoteNotificationFetchCompletionHandler:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications handleActionWithIdentifierForRemoteNotificationCompletionHandler:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications didReceiveLocalNotification:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications handleActionWithIdentifierForLocalNotificationCompletionHandler:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications didFinishLaunchingWithOptions:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications continueUserActivity:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications openURL:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications openURLOptions:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications performActionForShortcutItem:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications delegate]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications setDelegate:]
warning: (arm64)  could not find object file symbol for symbol -[DTNotifications .cxx_destruct]
warning: (arm64)  could not find object file symbol for symbol __OBJC_$_CLASS_METHODS_DTNotifications
warning: (arm64)  could not find object file symbol for symbol __OBJC_METACLASS_RO_$_DTNotifications
warning: (arm64)  could not find object file symbol for symbol __OBJC_$_INSTANCE_METHODS_DTNotifications
warning: (arm64)  could not find object file symbol for symbol __OBJC_$_INSTANCE_VARIABLES_DTNotifications
warning: (arm64)  could not find object file symbol for symbol __OBJC_$_PROP_LIST_DTNotifications
warning: (arm64)  could not find object file symbol for symbol __OBJC_CLASS_RO_$_DTNotifications
warning: (arm64)  could not find object file symbol for symbol _OBJC_IVAR_$_DTNotifications._firstLaunch
warning: (arm64)  could not find object file symbol for symbol _OBJC_IVAR_$_DTNotifications._lastProcessedLaunchOptions
warning: (arm64)  could not find object file symbol for symbol _OBJC_IVAR_$_DTNotifications.delegate
warning: (arm64)  could not find object file symbol for symbol _OBJC_CLASS_$_DTNotifications
warning: (arm64)  could not find object file symbol for symbol _OBJC_METACLASS_$_DTNotifications
warning: (arm64)  could not find object file symbol for symbol __dt_launchOptions
warning: (arm64)  could not find object file symbol for symbol __didFinishLaunchingWithOptionsProcessed
warning: (arm64) /tmp/bitcode_strip.FGcSsS unable to open object file: No such file or directory
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils iosVersion]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils debug:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils log:message:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils dispatchStatusEvent:code:level:]
warning: (arm64)  could not find object file symbol for symbol ___45+[DTFREUtils dispatchStatusEvent:code:level:]_block_invoke
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectAsString:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectAsInt:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectAsBoolean:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectAsNSData:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectAsDouble:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectAsArrayOfStrings:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectAsArrayOfNumbers:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectAsArrayOfDoubles:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectAsArrayOfBooleans:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectAsJSONDict:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREArrayFromStringArray:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils keyValueStringFREArraysToNSDictionary:values:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils keyValueArraysToNSDictionary:values:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectPropertyAsString:object:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectPropertyAsBoolean:object:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectPropertyAsInt:object:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectPropertyAsDouble:object:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getFREObjectPropertyAsObject:object:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREObjectFromObject:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREObjectFromString:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREObjectFromInt:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREObjectFromLong:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREObjectFromBoolean:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREObjectFromDouble:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREObjectFromNSUInteger:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREObjectFromNSInteger:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREObjectFromNSNumber:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREObjectFromNSData:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils newFREObject]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils setFREObjectProperty:object:value:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils colorFromRGB:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils colorFromARGB:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils getRootViewController]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils currentViewController]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils drawCGImageRefToBitmapData:bitmapData:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils drawUIImageToBitmapData:bitmapData:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils createUIImageFromBitmapData:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils createUIImageFromBitmapData:scale:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils initDataWithString:]
warning: (arm64)  could not find object file symbol for symbol +[DTFREUtils base64EncodedStringFromNSData:]
warning: (arm64)  could not find object file symbol for symbol __OBJC_$_CLASS_METHODS_DTFREUtils
warning: (arm64)  could not find object file symbol for symbol __OBJC_METACLASS_RO_$_DTFREUtils
warning: (arm64)  could not find object file symbol for symbol __OBJC_CLASS_RO_$_DTFREUtils
warning: (arm64)  could not find object file symbol for symbol _OBJC_CLASS_$_DTFREUtils
warning: (arm64)  could not find object file symbol for symbol _OBJC_METACLASS_$_DTFREUtils
warning: (arm64) /tmp/bitcode_strip.u69A0i unable to open object file: No such file or directory
warning: (arm64)  could not find object file symbol for symbol _DTTAG_TAG
warning: (arm64)  could not find object file symbol for symbol __OBJC_METACLASS_RO_$_DTTag
warning: (arm64)  could not find object file symbol for symbol __OBJC_CLASS_RO_$_DTTag
warning: (arm64)  could not find object file symbol for symbol _OBJC_METACLASS_$_DTTag
warning: (arm64)  could not find object file symbol for symbol _OBJC_CLASS_$_DTTag
warning: (arm64) /tmp/bitcode_strip.oW8Z0j unable to open object file: No such file or directory
warning: (arm64)  could not find object file symbol for symbol +[DTExtensionBase v:identifier:]
warning: (arm64)  could not find object file symbol for symbol __OBJC_$_CLASS_METHODS_DTExtensionBase
warning: (arm64)  could not find object file symbol for symbol __OBJC_METACLASS_RO_$_DTExtensionBase
warning: (arm64)  could not find object file symbol for symbol __OBJC_CLASS_RO_$_DTExtensionBase
warning: (arm64)  could not find object file symbol for symbol _OBJC_METACLASS_$_DTExtensionBase
warning: (arm64)  could not find object file symbol for symbol _OBJC_CLASS_$_DTExtensionBase


Codesign request for IPA: codesign --force --sign ee9e3da2872853fd281fe192c46e2fde3fec6c94 --entitlements /var/folders/70/c91x_vtj0t31vyvyn__jqqdw0000gn/T/3c7a2233-deb9-4611-a21d-fa273ba5da1e/entitlement10348914760414001883xcent --generate-entitlement-der /var/folders/70/c91x_vtj0t31vyvyn__jqqdw0000gn/T/3c7a2233-deb9-4611-a21d-fa273ba5da1e/Payload/3DTuning.app


```

**Comment by Tuning3DT** [comment]
> That linker command looked good:
> 
> ```
> ld64 command line:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld-classic
> -syslibroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk"
> -L/usr/lib -L/usr/lib/swift -F"/System/Library/Frameworks"
> ...
> -platform_version ios 12.2 17.4 
> ...
> ```
> 
> So it's using the Xcode classic (ld64) linker, with the right 17.4 iPhoneOS SDK and system libraries, with correct platform version details etc...
> 
> Is it possible to run this build on a phone and then get the IPS file from it after the crash (from Settings -> Privacy & Security -> Analytics & Improvements -> Analytics Data, and find the timestamped crash file and 'send' from your phone)?
> 
> thanks
Thanks for replying so quickly. 
[3DTuning-2024-05-01-192037.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15178539/3DTuning-2024-05-01-192037.txt)

**Comment by Tuning3DT** [comment]
@ajwfrost thanks a lot for your help, I finally managed to build a properly working IPA.

**Comment by Tuning3DT** [comment]
@ajwfrost I finally managed to resolve the crash on launch but the crashes are still high.

[com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_87ac680891e74a1e97d19eb1d18c1ba5_DNE_0_v2_stacktrace.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15183491/com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_87ac680891e74a1e97d19eb1d18c1ba5_DNE_0_v2_stacktrace.txt)
[com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_a814c35675ae45f99d7aea952cce30f8_DNE_0_v2_stacktrace.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15183493/com.3dtuning.Tuning3D_issue_3ceba855a8ad2d1af83655803dc13f70_crash_session_a814c35675ae45f99d7aea952cce30f8_DNE_0_v2_stacktrace.txt)


[com.3dtuning.Tuning3D_issue_f8b447e7b60a2c1c4daa60a84db7adc1_crash_session_3a5f66292add404ea46de16b5ba76642_DNE_0_v2_stacktrace.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15183523/com.3dtuning.Tuning3D_issue_f8b447e7b60a2c1c4daa60a84db7adc1_crash_session_3a5f66292add404ea46de16b5ba76642_DNE_0_v2_stacktrace.txt)
[com.3dtuning.Tuning3D_issue_f8b447e7b60a2c1c4daa60a84db7adc1_crash_session_f23b7f1ce0cb41f09c1b6ef9b2e10734_DNE_0_v2_stacktrace.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15183524/com.3dtuning.Tuning3D_issue_f8b447e7b60a2c1c4daa60a84db7adc1_crash_session_f23b7f1ce0cb41f09c1b6ef9b2e10734_DNE_0_v2_stacktrace.txt)

**Comment by Tuning3DT** [comment]
I tried to build with old 50.2.3.1 AIR SDK pointing to the new iOS SDK, but Apple won't let me upload it. 
Looks like it omits the pointed iOS SDK and uses AIR SDK's build in one.
`iOSPlatformSDK=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk`

```
Asset validation failed (90725)
SDK version issue. This app was built with the iOS 12.2 SDK. 
All iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution. 
(ID: e84082ed-f9d7-41db-89c3-38a6d34ef55f)
```

**Comment by Tuning3DT** [comment]
I tried to build with old 50.2.3.1 AIR SDK pointing to the new iOS SDK, but Apple won't let me upload it.
Looks like it reads the minimum iOS SDK version as the version it was build with. 
`iOSPlatformSDK=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk`

```
Asset validation failed (90725)
SDK version issue. This app was built with the iOS 12.2 SDK. All iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution. (ID: 22d8be37-2ed9-4112-86be-76f4d79345e5)
```
This is the sdk manager troubleshooting report
[troubleshooting.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15185381/troubleshooting.txt)

**Comment by ajwfrost** [comment]
Hi

Are you able to provide an IPS report for one of those crashes please? They look again like they're happening in different places .. presumably these are crashes during operation, can I check if you're using HTTPS connections within the app as there's some indication that URL callbacks are happening..

One thing you could try is to use an older version of the AIR SDK but copy in the adt.jar file from the later builds. The version codes that are embedded into the binary are (currently) taken from a set of constants within ADT... the challenge then being that the linker mechanisms may also be different in the older AIR SDK versions.

If you build the app with the older AIR SDK, is it stable on your own devices? vs building with the newer settings, it's unstable? Leaving aside the separate issue of whether or not Apple Play Store allows the binary, which we should be able to sort out (with a patch if needs be)..

thanks

**Comment by Tuning3DT** [comment]
Yes , the app build with 50.2.3.1 is very stable. crashes are around 20 times less compared to the one build with 50.2.4.5

**Comment by Tuning3DT** [comment]
@ajwfrost I replaced 50.2.3.1 AIRSDK/lib/adt.jar with 50.2.4.5 art.jar and it won't let me package the IPA. 
Here is the error 

`Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/asn1/ASN1Encodable at com.adobe.air.ADT.parseNativeSigningOptions(ADT.java) at com.adobe.air.ADT.parsePackage(ADT.java) at com.adobe.air.ADT.parseArgsAndGo(ADT.java) at com.adobe.air.ADT.run(ADT.java) at com.adobe.air.ADT.main(ADT.java) Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.ASN1Encodable at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 5 more`

**Comment by ajwfrost** [comment]
Ah - sorry, yes you will also need to copy over a folder in the new SDK, "lib/bouncycastle" which has these third party libraries in there for signing the IPAs..

We'll do a check between 50.2.3.1 and 50.2.4.5 to see what changes may be causing instabilities. I'd be willing to bet it's around the URL/HTTPS area...

thanks

**Comment by Tuning3DT** [comment]
Thanks @ajwfrost , I successfully build with the old SDK.
Here is an IPS
[3DTuning-2024-05-02-124814.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15186972/3DTuning-2024-05-02-124814.txt)

**Comment by Tuning3DT** [comment]
@ajwfrost thanks a lot for your help and support. The "objc_msgSend" related crash issue is solved. The percentage of crashes dropped down after compiling with the old stable AIR SDK.
However with this version increased new types of crashes. Not as much as the previous one. Here are some stack traces.

[com.3dtuning.Tuning3D_issue_f8b447e7b60a2c1c4daa60a84db7adc1_crash_session_09caec5dc8644077a8c96832776c2b47_DNE_0_v2_stacktrace.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15196805/com.3dtuning.Tuning3D_issue_f8b447e7b60a2c1c4daa60a84db7adc1_crash_session_09caec5dc8644077a8c96832776c2b47_DNE_0_v2_stacktrace.txt)
[com.3dtuning.Tuning3D_issue_f8b447e7b60a2c1c4daa60a84db7adc1_crash_session_dcdc3578f79d4a168794a3c607ca2d63_DNE_0_v2_stacktrace.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15196806/com.3dtuning.Tuning3D_issue_f8b447e7b60a2c1c4daa60a84db7adc1_crash_session_dcdc3578f79d4a168794a3c607ca2d63_DNE_0_v2_stacktrace.txt)
[com.3dtuning.Tuning3D_issue_f8b447e7b60a2c1c4daa60a84db7adc1_crash_session_cf56a46a9fdc4d20b1e30cf3ebf52eeb_DNE_0_v2_stacktrace.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/15196807/com.3dtuning.Tuning3D_issue_f8b447e7b60a2c1c4daa60a84db7adc1_crash_session_cf56a46a9fdc4d20b1e30cf3ebf52eeb_DNE_0_v2_stacktrace.txt)

**Comment by ajwfrost** [comment]
Hmm.. all three of those are in:
```
Crashed: com.apple.main-thread
0  3DTuning                       0x31db38 main + 2238920
1  libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
```
Will see if we can work out what's happening there, but I'm wondering whether there's any way we could get your compiled set-up to be able to then package/link it here with a debug runtime... will talk with one of my colleagues about this one...

thanks

**Comment by Tuning3DT** [comment]
Sure, I will send you it by email.
