### ISSUE TITLE
Input line is too long

### ISSUE THREAD

**Issue by marchbold** [airsdk/Adobe-Runtime-Support#360]
## Problem Description

Currently when using Windows for development for an iOS or Android application it is possible to hit the command line character limit when using a decent number of extensions.

This results in an error like:

```
Input line is too long.
Input line is too long.
```

## Steps to Reproduce

The approach to reproduce is to just add enough length to the command line to hit the Windows command line character limit. With a decent number of extensions this is hit even with normal project structure

- Create a project in a normal directory structure: eg `C:\work\projects\projectname\source`
- Add around 15+ extensions
- Attempt to package

## Known Workarounds

There are several approaches to get around this.

Firstly is to make the absolute path to the project as short as possible. 

Eg work from a project directory:

```
C:\d\
```

Often this isn't even enough.

Secondly, limit the number of extensions in use, but this often either limits the functionality available to the app or means a developer has to be able to have the skills to combine multiple extensions into one (Not simple).

## Feature

I'm not sure exactly which part of the SDK packaging is causing this issue but was wondering whether it is possible to provide a directory of extensions as an argument rather than each extension individually getting added to the command line, as the number of extensions seems to be the issue here.

Reference: https://github.com/distriqt/ANE-Firebase/issues/293

**Comment by FliplineStudios** [comment]
Is this with using ADT's package command?  We've used the -extdir option and put all of our project's ANEs in the directory we specify there, so we don't have to list them all individually that way.  Or does the same issue appear even when using -extdir?

**Comment by marchbold** [comment]
Apologies, I should have made that clear, we have all the extensions in one directory, and using the `-extdir` option to adt. However it seems one of the internal commands appends each extension in the extdir to the command line.

**Comment by ajwfrost** [comment]
Internally there look to be two commands we call that have a command line dependent on the number of extensions:

1) AAPT - using "-S tmp_res_folder" to include any resources embedded in an ANE
2) D8 (formerly DX) - passing in all the JAR files both that we generate and from the ANEs
This latter one looks like it's the longer one, but we can look to see if it's possible to pass things in via a file input, or to split up the operations into increments.
Potentially we can make some reductions in the command-line on Windows by better use of working folders so we don't have to have the full path names used..

**Comment by marchbold** [comment]
The error seems to appear twice as well, so probably indicates both places are an issue. Also note, this happens for Android **and iOS apps**.

**Comment by dmshykhaliiev** [comment]
Hello, is there any update on this issue?

**Comment by ajwfrost** [comment]
Hi - this is in our queue, we've just brought on board a new Java specialist who will be addressing some of these ADT-specific issues..

**Comment by dmshykhaliiev** [comment]
Thanks for the reply, is it possible to get an estimate, when could the fix be released?

**Comment by ajwfrost** [comment]
We'd been planning for a release in September (after our patch-release coming out shortly) so should get a change in there.

FYI - another workaround might be to use a different "TMP" environment variable, mine by default is c:\users\username\appdata\local\temp, but we save space on the command line if 'TMP' points instead to c:\temp.

(which has made me notice that we also seem to not be cleaning up properly..?! will add that to the list of things to investigate.....)

**Comment by dmshykhaliiev** [comment]
Thanks a lot! Will try this workaround and will wait for September :)

**Comment by AleBles** [comment]
Was there any progress on this issue? I'm running into the same issue, specifically for iOS builds (Android runs. fine)

**Comment by marchbold** [comment]
@ajwfrost Would the linker options and packaged dependencies in an ANE contribute here? eg if I had the same linker option in multiple ANEs ? Just having this issue with one of our clients currently and can't seem to get around it this time.

**Comment by ajwfrost** [comment]
@marchbold sorry this one seems to have slipped out of our backlog, it has probably been mis-tagged, I'll try to get that pulled back in! Regarding the above: yes I believe that ADT just builds up a long command by adding any linker options from the ANEs into the list of command-line options. So if you can remove duplicate entries by changing those, it would probably help. I'll get someone to look again to see if we can do this via an options file..

**Comment by ajwfrost** [comment]
Hi again - just checking, is this specifically for Android? as we're changing how we do the packaging for Android anyway, which would remove the long command-lines...

**Comment by marchbold** [comment]
mainly seem to have the issue on iOS currently... Android is actually building fine with many more ANEs.

obviously I can't generally change these linker options as it depends on the combination of ANEs in use so definitely could be some optimisation in removing duplicates within ADT?

**Comment by marchbold** [comment]
Just FYI, removing duplicate linker options from the ane's we were using in this project helped. 

So can we request that this is done internally by AIR?

**Comment by ajwfrost** [comment]
Thanks - yes I've asked someone to look at this approach and also to see whether there are other options that we could use to completely eliminate this issue.

**Comment by megajogos** [comment]
We have the same error here!

**Comment by jimmymjing** [comment]
Hello, I'm having the same issue. Please fix it. Thanks so much!

**Comment by shaymolho** [comment]
@ajwfrost  still happens with latest AIR 50.2.2.5 ( 28-Apr-2023 )

**Comment by ajwfrost** [comment]
@shaymolho are you able to grab a patch file from the link below and see if this helps?
https://transfer.harman.com/message/06gKCID0BYqTRmKlmK590Y


thanks

**Comment by shaymolho** [comment]
@ajwfrost this one solves the previous "input line is too long" problem, however it fails on something else that I will report to @marchbold  related to unity ads mediaion.
attached adt.log again.
[adt.log](https://github.com/airsdk/Adobe-Runtime-Support/files/11471445/adt.log)

**Comment by ajwfrost** [comment]
Thanks -> the "_objc_msgSend" failures I think may just mean you need the latest ANE? There's a change in Xcode 14 linker outputs which caused these problems, but there is a flag you (well, we + ANE developers) can use to force the older symbols to be used. The new ones aren't supported by the "ld64" linker on Windows (and not much we can do here, unless Apple have more recently published their linker changes to the open source version..)

thanks

**Comment by marchbold** [comment]
We should have already updated these extensions to include that flag, make sure you are using the latest, otherwise it might be a separate issue?

**Comment by shaymolho** [comment]
@ajwfrost was the patch published to the official air release? I started getting this again

**Comment by ajwfrost** [comment]
Yes it was in 50.2.2.6... so if you're getting an "input line is too long" error, it may be something else that's causing the long line (we had just been looking to remove duplicate entries and shrink things down as much as possible..)

Are you able to find out that the command line is, that's causing the problems? E.g. via AIR SDK Manager, troubleshooting page? We can see what other optimisations we can perhaps do for this one..

thanks

**Comment by shaymolho** [comment]
for some reason I'm not getting adt.log
I removed the comment out from this file int `lib/adt.cfg`:
`DebugOut=true`

**Comment by ajwfrost** [comment]
The config file is now in `~/.airsdk/` folder (well, if there isn't one there, we'd read it from the SDK lib folder, but the .airsdk one is the preference/priority..).

**Comment by shaymolho** [comment]
it still doesn't log
here is my adt.cfg located both in .airsdk and in air sdk lib:

**Comment by ajwfrost** [comment]
Ah .. was just writing that the config file looked okay. We haven't got a different folder, but if you have (or can get) the AIR SDK Manager, you can click on the "Troubleshooting" tab and the logs will be sent to that...

thanks

**Comment by shaymolho** [comment]
here is my adt.log
https://gist.github.com/shaymolho/dbe3ebc8d81a49da8f19c85f18e21cbc

**Comment by ajwfrost** [comment]
Hmm.. a lot of ANEs! 11355 characters (ish). Looking for optimisations..

26x instances of the temp folder, which is 44 characters, it may be possible for you to change the temp variable to c:\\tmp (7 chars) and save 962 characters. But that's still loads more than 8191.. 

71x exported symbols. This may actually be something we can switch to using a file for, like we have for the object files list. That would save a fair amount, over 2000 at least which gets us close. 

25x framework folders .. each of which are under the temp folder and then under a guid-style unique folder. I'm wondering whether we could actually just have one temp folder for all frameworks, and then only need this in there once! This could save a fair bit, around 1175 on top of the earlier changes to use c:\\tmp...

168x `-framework` directives. Sadly there doesn't seem to be any way to provide these via a list file, or to have a shorter `--f` type option for including them.


So it looks like there could be more we can do here. The other thing to consider is if we do ever manage to build the Apple linker for Windows ourselves, then we would be free to change how all this works so could take all of the inputs from a file rather than the command-line...

In the meantime we'll look at the second and third options here and get them into ADT..

thanks

**Comment by shaymolho** [comment]
thank you for the detailed answer
I also noticed there are some duplicate framework directives (`-framework AVFoundation` appears 7 times for example) 
maybe there's an optimization that could eliminate these duplicates as well

**Comment by shaymolho** [comment]
is there any option to increase the 8192 limit?

**Comment by ajwfrost** [comment]
Hmmm:
> I also noticed there are some duplicate framework directives (-framework AVFoundation appears 7 times for example)

That's meant to already be in place! Just checked the code and I'm not sure how that would have got through..

> is there any option to increase the 8192 limit?

Sadly that's just a Windows command-line limit, and we're calling a Windows application (ld64) with all these arguments..
https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation

**Comment by shaymolho** [comment]
can u try to solve the duplicate frameworks again? i think that would solve the issue

**Comment by ajwfrost** [comment]
We found why that bit wasn't working .. but also have made a few other tweaks per the above. Preview build is below within the zip... (just unzip and put this jar file into the SDK "lib" folder)

thanks

[adt.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/12525553/adt.zip)

**Comment by shaymolho** [comment]
now getting a different error:
`ld: file is universal (4 slices) but does not contain the arm64 architecture: C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\7a339ac5-d772-4b0c-98b4-6faa3679c05b/FBAudienceNetwork.framework/FBAudienceNetwork for architecture arm64
`
adt.log:
https://gist.github.com/shaymolho/d627ef6457a47b3df82ab981a7bf46d4

**Comment by ajwfrost** [comment]
If that's the distriqt ANE (com.distriqt.admob.FacebookAudience) then when I check that file, it's got two slices, armv7 and arm64 which is what I'd expect. Are you able to check it there -> if you have the ANE, open it in a zip manager and extract the folder `META-INF\ANE\iPhone-ARM\FBAudienceNetwork.framework`

Then you can run the below (with my output, with the ANE just downloaded)
```
> AIRSDK\lib\aot\bin\lipo\lipo.exe -info FBAudienceNetwork.framework\FBAudienceNetwork

DATA addr 00BF0000
Architectures in the fat file: FBAudienceNetwork.framework\FBAudienceNetwork are: armv7 arm64
```

If you see something different, it may be worth getting the latest ANE; if this does show arm64 though, then we have another issue here :-(

thanks

**Comment by shaymolho** [comment]
I will open a separate issue for that if needed
the `Input line is too long` is solved for now
@marchbold can u close this one?

**Comment by marchbold** [comment]
@shaymolho will close when the fix is released. 

Let me know if there's something amiss with the fb audience network framework.

**Comment by itlancer** [comment]
@ajwfrost, with latest AIR SDK 50.2.3.5 when I try to package application that used native extension with framework that only support arm64 in result I got error:
```
ld: framework not found my_native_extension
Compilation failed while executing : ld64
```
All works fine with AIR SDK 50.2.3.4 and earlier.

**Comment by marchbold** [comment]
Resolved in 50.2.3.6

**Comment by itlancer** [comment]
```
ld: framework not found my_native_extension
Compilation failed while executing : ld64
```
Also fixed with latest AIR SDK 50.2.3.6 for Windows and patch https://github.com/distriqt/ANE-GooglePlayServices/issues/28#issuecomment-1744230616
